USE [master]
GO

/****** Object:  Database [DexterJitterData]    Script Date: 12-02-2024 11:38:06 ******/
CREATE DATABASE [DexterJitterData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DexterJitterData', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DexterJitterData.mdf' , SIZE = 270336KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DexterJitterData_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DexterJitterData_log.ldf' , SIZE = 663552KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DexterJitterData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DexterJitterData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DexterJitterData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DexterJitterData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DexterJitterData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DexterJitterData] SET ARITHABORT OFF 
GO

ALTER DATABASE [DexterJitterData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DexterJitterData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DexterJitterData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DexterJitterData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DexterJitterData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DexterJitterData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DexterJitterData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DexterJitterData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DexterJitterData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DexterJitterData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DexterJitterData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DexterJitterData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DexterJitterData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DexterJitterData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DexterJitterData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DexterJitterData] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DexterJitterData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DexterJitterData] SET RECOVERY FULL 
GO

ALTER DATABASE [DexterJitterData] SET  MULTI_USER 
GO

ALTER DATABASE [DexterJitterData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DexterJitterData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DexterJitterData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DexterJitterData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DexterJitterData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DexterJitterData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DexterJitterData] SET  READ_WRITE 
GO


