USE [master]
GO

/****** Object:  Database [ThirdLineQs]    Script Date: 14-02-2025 13:59:33 ******/
CREATE DATABASE [ThirdLineQs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ThirdLineQs', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ThirdLineQs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ThirdLineQs_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ThirdLineQs_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ThirdLineQs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ThirdLineQs] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ThirdLineQs] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ThirdLineQs] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ThirdLineQs] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ThirdLineQs] SET ARITHABORT OFF 
GO

ALTER DATABASE [ThirdLineQs] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ThirdLineQs] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ThirdLineQs] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ThirdLineQs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ThirdLineQs] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ThirdLineQs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ThirdLineQs] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ThirdLineQs] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ThirdLineQs] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ThirdLineQs] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ThirdLineQs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ThirdLineQs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ThirdLineQs] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ThirdLineQs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ThirdLineQs] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ThirdLineQs] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ThirdLineQs] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ThirdLineQs] SET RECOVERY FULL 
GO

ALTER DATABASE [ThirdLineQs] SET  MULTI_USER 
GO

ALTER DATABASE [ThirdLineQs] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ThirdLineQs] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ThirdLineQs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ThirdLineQs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ThirdLineQs] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ThirdLineQs] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ThirdLineQs] SET  READ_WRITE 
GO


