USE [FiEvents]
GO

/****** Object:  Table [dbo].[EventTexts]    Script Date: 12-11-2020 11:03:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EventTexts](
	[EventTextId] [int] IDENTITY(1,1) NOT NULL,
	[EventCode] [nvarchar](20) NOT NULL,
	[EventText] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_EventTexts] PRIMARY KEY CLUSTERED 
(
	[EventTextId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


